services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile.production
    ports:
      - "80:80"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_GITHUB_USERNAME=${NEXT_PUBLIC_GITHUB_USERNAME}
      - NEXT_PUBLIC_DISCORD_USER_ID=${NEXT_PUBLIC_DISCORD_USER_ID}
      - NEXT_PUBLIC_DISCORD_USERNAME=${NEXT_PUBLIC_DISCORD_USERNAME}
      - NEXT_PUBLIC_DISCORD_DISPLAY_NAME=${NEXT_PUBLIC_DISCORD_DISPLAY_NAME}
      - NEXT_PUBLIC_DISCORD_CLIENT_ID=${NEXT_PUBLIC_DISCORD_CLIENT_ID}
      - NEXT_PUBLIC_SPOTIFY_CLIENT_ID=${NEXT_PUBLIC_SPOTIFY_CLIENT_ID}
      - NEXT_PUBLIC_PROD_URL=${NEXT_PUBLIC_PROD_URL}
      - NEXT_PUBLIC_DEV_URL=${NEXT_PUBLIC_DEV_URL}
      - NEXT_PUBLIC_SPOTIFY_REDIRECT_URI=${NEXT_PUBLIC_SPOTIFY_REDIRECT_URI}
      - DISCORD_CLIENT_SECRET=${DISCORD_CLIENT_SECRET}
      - ADMIN_API_KEY=${ADMIN_API_KEY}
    volumes:
      - ./data:/app/data
    restart: unless-stopped

networks:
  default:
    name: domkutis-network 